### ISSUE TITLE
Rainbow Table 描述

### ISSUE THREAD

**Issue by cmj0121** [Inndy/fresh-foods#1]
彩虹表的描述中應該要著重在如何產生出 hash chain，因為從目前這個版本的描述中，給讀者的感覺會是建立一個 index table，但是這不是 rainbow table 主要的精神。如果只是建立一個 full index table 的話，rainbow table 就單純地用空間換取時間，但按照你的例子 (000 - ZZZZZZZZZ)，會得到
- 長度 3 ~ 9 的字串
- 輸入直可能是數字/大小寫字母

這樣會有約有 2 **37 個資料量，如果是用 MD5 來參考的話 2**42 bytes ~= 4TB，但是從 [這個 link](http://project-rainbowcrack.com/table.htm) 可以看到不到 700GB

**Comment by Inndy** [comment]
感謝提醒，我其實不太了解彩虹表背後的細節，之後會修正相關的說法
