### ISSUE TITLE
連結失效

### ISSUE THREAD

**Issue by racterub** [Inndy/fresh-foods#3]
000-201607-1.不要儲存明文密碼.md
中的MD5以及SHA連結都以失效QQ

**Comment by Inndy** [comment]
我看都是好的，試試看 [Internet Archive](http://web.archive.org/web/*/http://www.infosec.sdu.edu.cn/2person_wangxiaoyun.htm) 或是 Google cache，你可能被 GFW 牆了

**Comment by racterub** [comment]
現在看又是好的@@見鬼了..
感謝
